import './globals.css';
import { Header } from './components/Header';

export const metadata = {
  title: 'IMDB CLONE',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* Header */}

      {/* Navbar */}
      {/* SearchBox */}
      <body className='m-6'>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
